project:
  type: book

lang: zh

book:
  title: "现代应用统计"
  output-file: "masr"
  author: "黄湘云"
  date: "2022-04-05"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "机器学习"
      chapters:
        - classification-problems.qmd
        - clustering-problems.qmd
        - regression-problems.qmd
    - part: "贝叶斯建模"
      chapters:
        - probabilistic-reasoning-framework.qmd
        - generalized-linear-models.qmd
        - hierarchical-normal-models.qmd
        - mixed-effects-models.qmd
        - generalized-additive-models.qmd
        - gaussian-processes-regression.qmd
        - time-series-regression.qmd
    - part: "空间分析"
      chapters:
        - analyze-point-pattern.qmd
        - analyze-spatial-data.qmd
        - analyze-areal-data.qmd
    - references.qmd
  appendices:
    - notations.qmd
    - matrix-operations.qmd
  repo-branch: main
  search: true
  downloads: [pdf]

bibliography:
  - references.bib
  - packages.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    crossref:
      chapters: true
  docx:
    toc: true
    toc-depth: 3
    crossref:
      chapters: true
  pdf:
    documentclass: book
    include-in-header: preamble.tex
    include-before-body:
      text: |
        \ifdefined\appendixname
          \renewcommand*\appendixname{附录}
        \else
          \newcommand\appendixname{附录}
        \fi
    include-after-body:
      text: |
        \printindex
    classoption:
      - UTF8
      - twoside
      - openany
      - table
    keep-tex: true
    latex-auto-install: false
    mathspec: true
    lof: true
    lot: true
    geometry:
      - tmargin=2.5cm
      - bmargin=2.5cm
      - lmargin=3.0cm
      - rmargin=2.0cm
    highlight-style: github
    number-sections: true
    top-level-division: chapter
    colorlinks: true
    link-citations: true
    crossref:
      chapters: true

editor: source
