# 符号约定 {#sec-math-notations}

::: hidden
$$
 \def\bm#1{{\boldsymbol #1}}
$$
:::

| 符号                     | 含义                 |
|--------------------------|----------------------|
| $\mathbb{R}^n$           | $n$ 维实数           |
| $\mathbb{R}^{n\times p}$ | $n\times p$ 维实矩阵 |
| $\mathbb{Z}$             | 整数                 |
| $\mathcal{N}$            | 正态分布             |
| $\mathcal{D}$            | 研究区域             |
| $\mathcal{S}$            | 随机过程             |
| $\mathcal{G}$            | 图                   |
| $\mathcal{L}$            | 似然                 |
| $\mathrm{MVN}$           | 多元正态分布         |
| $\Sigma$                 | 协方差矩阵           |
| $x$                      | 标量                 |
| $\bm{x}$                 | 向量                 |
| $X$                      | 矩阵                 |
| $X^{\top}$               | 矩阵转置             |
| $X^{-1}$                 | 矩阵求逆             |
| $I$                      | 单位矩阵             |
| $J$                      | 全 1 矩阵            |
| $\bm{1}$                 | 全 1 向量            |
| $\bm{0}$                 | 全 0 向量            |
| $\beta$                  | 截距                 |
| $\bm{\beta}$             | 系数向量             |
| $\ell$                   | 对数似然             |
| $\mathsf{E}$             | 期望                 |
| $\mathsf{Var}$           | 方差                 |
| $\mathsf{Cov}$           | 协方差               |
| $\mathrm{Bernoulli}$     | 伯努利分布           |
| $\mathrm{Binomial}$      | 二项分布             |
| $\mathrm{Poisson}$       | 泊松分布             |
| $\mathrm{Gamma}$         | 伽马分布             |
| $\mathrm{Beta}$          | 贝塔分布             |
| $\Gamma$                 | 伽马函数             |
| $\|\bm{x}\|_0$           | 向量的 0 范数        |
| $\|\bm{x}\|_1$           | 向量的 1 范数        |
| $\|\bm{x}\|_2$           | 向量的 2 范数        |
| $\|\bm{x}\|_p$           | 向量的 $p$ 范数      |

: 数学符号表 {#tbl-math-symbols}

全书英文字母表示数据，希腊字母表示参数，加粗表示向量，大写表示矩阵，花体字母各有含义。所有的向量都是列向量，如上表中的 $\bm{x}$ ，而 $\bm{x}^{\top}$ 则表示行向量。

下表给出本书用到的一些统计术语的英文缩写。

| 统计术语                | 英文                                            | 英文缩写 |
|------------------------|------------------------|------------------------|
| 最小二乘估计            | Least Squares Estimator                         | LSE      |
| 极大似然估计            | Maximum Likelihood Estimation                   | MLE      |
| 最佳线性无偏估计        | Best Linear Unbaised Estimator                  | BLUE     |
| 最小方差无偏估计        | Minimum-Variance Unbiased Estimator             | MVUE     |
| 一致最小方差无偏估计    | Uniformly Minimum-Variance Unbiased Estimator   | UMVUE    |
| 最小范数二次无偏估计    | Minimum Norm Quadratic Unbiased Estimator       | MINQUE   |
| 普通最小二乘估计        | Ordinary Least Squares Estimator                | OLS      |
| 偏最小二乘估计          | Partial Least Squares Estimator                 | PLS      |
| 广义最小二乘估计        | Generalized Least Squares Estimator             | GLS      |
| 带权最小二乘估计        | Weighted Least Squares Estimator                | WLS      |
| 迭代再加权最小二乘      | Iteratively Reweighted Least Squares            | IRLS     |
| 最小绝对收缩和选择算子  | Least Absolute Shrinkage and Selection Operator | LASSO    |
| 均方误差                | Mean Squared Error                              | MSE      |
| 均方根误差              | Root Mean Squared Error                         | RMSE     |
| 平均绝对误差            | Mean Absolute Error                             | MAE      |
| 最小绝对误差            | Least Absolute Error                            | LAE      |
| 惩罚拟似然              | Penalized Quasi-Likelihood                      | PQL      |
| 剖面极大似然            | Profile Maximum Likelihood                      | PML      |
| 限制极大似然            | REstricted Maximum Likelihood                   | REML     |
| 广义估计方程            | Generalized Estimating Equation                 | GEE      |
| 线性模型                | Linear Models                                   | LM       |
| 广义线性模型            | Generalized Linear Models                       | GLM      |
| 广义可加模型            | Generalized Additive Models                     | GAM      |
| 线性混合效应模型        | Linear Mixed-Effects Models                     | LMM      |
| 非线性混合效应模型      | Nonlinear Mixed-Effects Models                  | NLME     |
| 广义线性混合效应模型    | Generalized Linear Mixed-Effects Models         | GLMM     |
| 广义可加混合效应模型    | Generalized Additive Mixed-Effects Models       | GAMM     |
| 集成嵌套拉普拉斯        | Integrated Nested Laplace approximation         | INLA     |
| 马尔可夫链蒙特卡洛      | Markov Chain Monte Carlo                        | MCMC     |

: 统计术语的英文缩写 {#tbl-stats-acronym}
